#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-only

. config/options $1

if [ -z "$1" ]; then
  echo "usage: $0 package_name [-b]"
  exit 1
fi

check_package $1

case "$2" in
  -b)
    STAMP=$STAMPS/$PACKAGE_NAME/build_$TARGET
    STEP=BUILD
    $0 $1 -u
    ;;
  -u|"")
    STAMP=$PKG_BUILD/.unpack
    STEP=UNPACK
    ;;
esac

if [ -f $STAMP ] ; then
  rm -f $STAMP

  printf "%${BUILD_INDENT}c ${boldcyan}SKIP_$STEP${endcolor}   $1\n" ' '
  export BUILD_INDENT=$((${BUILD_INDENT:-1}+4))

  save_stamp
fi
